module.exports = {
  purge: ['./components/**/*.js', './pages/**/*.js'],
  whitelist: ['mode-dark'],
  theme: {
    extend: {
      padding: {
        dsk: '10%',
        nav: '4.7rem',
      },
      zIndex: {
        tenThous: '10000',
        thous: '1000',
        fiveHund: '500',
      },
      gridTemplateColumns: {
        experience: '1fr 2fr 1fr',
        chat: '40px 1fr',
        comment: '1fr 40px',
        userNav: '40px 1fr',
      },
    },
    colors: {
      transparentBlack: '#0d0d0df6',
      white: '#fff',
      black: '#0d0d0d',
      grey: '#7c7c7c',
      mediumGrey: '#8b8b8b',
      lightGrey: '#eaeaea',
      aqua: '#75cedb',
      purple: '#a891d9',
      muted: 'var(--color-muted)',
      'muted-hover': 'var(--color-muted-hover)',
      primary: 'var(--color-primary)',
      'primary-hover': 'var(--color-primary-hover)',
      secondary: 'var(--color-secondary)',
      'secondary-hover': 'var(--color-secondary-hover)',
      info: 'var(--color-info)',
      'info-hover': 'var(--color-info-hover)',
      success: 'var(--color-success)',
      'success-hover': 'var(--color-success-hover)',
      'success-background': 'var(--color-success-background)',
      warning: 'var(--color-warning)',
      'warning-hover': 'var(--color-warning-hover)',
      'warning-background': 'var(--color-warning-background)',
      danger: 'var(--color-danger)',
      'danger-hover': 'var(--color-danger-hover)',
      'danger-background': 'var(--color-danger-background)',
      background: 'var(--color-background)',
      'background-muted': 'var(--color-background-muted)',
      heading: 'var(--color-heading)',
      'heading-muted': 'var(--color-heading-muted)',
      body: 'var(--color-body)',
      'body-muted': 'var(--color-body-muted)',
    },
  },
  variants: {},
  plugins: [],
};
