export const defaultIcon =
  'https://oneoone-resource.s3.ap-northeast-2.amazonaws.com/yzed/account-icon.svg';

export const tokenName = 'firebaseToken';

export const userTerms = [
  "I'm baby pour-over biodiesel beard hammock occupy leggings bespoke activated charcoal VHS whatever hell of 8-bit raw denim PBR&B. Tilde listicle normcore bespoke neutra letterpress mumblecore chartreuse tote bag pour-over wayfarers biodiesel cloud bread activated charcoal. Church-key literally direct trade pabst, yuccie prism letterpress schlitz cornhole. Hella kitsch vape before they sold out lomo tumeric lo-fi DIY gluten-free offal snackwave. 90's scenester umami unicorn succulents single-origin coffee. Snackwave cred ennui small batch church-key quinoa authentic drinking vinegar wolf viral chambray woke brunch banjo heirloom.",
  "Chicharrones actually lyft, franzen kinfolk waistcoat echo park. Locavore air plant flannel flexitarian, food truck mustache affogato woke roof party. Affogato gluten-free woke pitchfork brunch whatever thundercats portland keytar vexillologist tofu ugh jianbing paleo. Franzen twee listicle vape williamsburg. Actually echo park lo-fi, leggings tbh wolf kogi gochujang waistcoat prism. 90's hell of meh meditation thundercats, before they sold out sriracha post-ironic hella chartreuse.",
  "Shaman vegan quinoa, humblebrag venmo waistcoat biodiesel twee godard single-origin coffee deep v authentic food truck live-edge farm-to-table. Marfa gochujang photo booth kale chips migas shoreditch chia blog master cleanse vice. Viral pitchfork franzen, +1 brunch jean shorts biodiesel chicharrones neutra pabst subway tile craft beer trust fund next level. Franzen plaid retro drinking vinegar pabst vexillologist viral deep v. Green juice seitan aesthetic tattooed woke pop-up. Hella paleo meggings, squid waistcoat fanny pack artisan jianbing vice you probably haven't heard of them tofu unicorn pop-up wayfarers cardigan.",
  "Schlitz gluten-free bespoke chartreuse meditation fixie kale chips shabby chic farm-to-table 90's tattooed street art wolf vegan jean shorts. Forage cold-pressed venmo dreamcatcher, prism +1 try-hard tacos mixtape taxidermy vice scenester disrupt. Next level asymmetrical cronut +1. Neutra bicycle rights heirloom la croix typewriter. Gentrify bespoke selfies, ennui franzen sartorial street art jianbing offal edison bulb try-hard locavore. Chartreuse yuccie YOLO everyday carry umami paleo.",
  'Readymade kickstarter jean shorts tumblr cray palo santo pinterest. Austin bushwick portland tbh edison bulb live-edge echo park paleo fixie, butcher tote bag. Hashtag green juice subway tile, schlitz butcher skateboard aesthetic. Schlitz jean shorts hot chicken polaroid. Occupy gluten-free hammock, affogato schlitz photo booth food truck seitan normcore enamel pin gastropub VHS leggings sartorial.',
];
